
enum TokenType  {

  //primitive type tokens
  TokenInteger,
  TokenChar,

  //n-nary operators tokens
  TokenPlus,
  TokenMinus,
  TokenMultiply,
  TokenDivide,
  TokenSwap,
  TokenAssign,
  TokenLessThanEquals,
  TokenLessThan,
  TokenGreaterThanEquals,
  TokenGreaterThan,
  TokenNotEquals,
  TokenEquals,
  TokenMod,
  TokenAnd,
  TokenOr,
  TokenNot,

  //colon, semicolong, comma, etc
  TokenColon,
  TokenSemiColon,
  TokenSingleDot,
  TokenComma,
  TokenOpenCurly,
  TokenCloseCurly,
  TokenLeftParent,
  TokenRightParent,
  TokenDoubleDot,

  //keywords token
  Token_NewLine,
  Token_Program,
  Token_Var,
  Token_Const,
  Token_Type,
  Token_Function,
  Token_Return,
  Token_Begin,
  Token_End,
  Token_Output,
  Token_If,
  Token_Then,
  Token_Else,
  Token_While,
  Token_Do,
  Token_Case,
  Token_Of,
  Token_Otherwise,
  Token_Repeat,
  Token_For,
  Token_Until,
  Token_Loop,
  Token_Pool,
  Token_Exit,
  Token_Read,
  Token_Succ,
  Token_Pred,
  Token_Chr,
  Token_Ord,
  Token_EOF,
  TokenWhiteSpace,
  TokenInvalidToken
};
